# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main, sprint1, sprint2, sprint3 ]
  push:
    branches: [ Sandbox ]

jobs:
  test_pull_request: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:         
          node-version: ${{ matrix.node-version }}
      - run: npm ci 
      - run: npm test

  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/src/tests
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/src